name: MacOS

on:
  workflow_dispatch:

jobs:
  test:
    name: Test on Python ${{ matrix.python-version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: [ 3.7, 3.8, 3.9, '3.10' ]
        os: [ macOS-latest ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r ./rl_interaction/requirements.txt

      - name: Install Appium
        run: |
          npm install -g appium appium-doctor
          appium-doctor --android

      - name: Setup test emulator
        run: |
          export PATH="${PATH}:${ANDROID_HOME}/tools/bin:${ANDROID_HOME}/platform-tools"
          sudo chmod a+x ${ANDROID_HOME}/tools/bin/avdmanager
          echo yes | sudo -E env "PATH=$PATH" sdkmanager "emulator" "system-images;android-25;default;x86" | grep -v = || true
          echo no | avdmanager create avd -f -n test -k "system-images;android-25;default;x86" --abi x86

      - name: Run tests
        run: |
          pytest test/ --verbose --cov=./ --cov-report xml
          echo '### Test report' >> $GITHUB_STEP_SUMMARY
          echo '' >> $GITHUB_STEP_SUMMARY
          echo '' >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          coverage report >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          echo '' >> $GITHUB_STEP_SUMMARY
          echo '### Test logs' >> $GITHUB_STEP_SUMMARY
          echo '' >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          cat logs/logger.log >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY

      - name: 压缩
        run: |
          zip -r build.zip .

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: build.zip
          path: ./build.zip
